export const pushNotifications = [
  {
    label: 'Everything',
    value: 'everything',
  },
  {
    label: 'Same as email',
    value: 'same as email',
  },
  {
    label: 'No push notifications',
    value: 'no push notifications',
  },
];
export const emailNotifications = [
  {
    label: 'Comments',
    value: 'everything',
  },
  {
    label: 'Candidates',
    value: 'candidate',
  },
  {
    label: 'Offers',
    value: 'Offers',
  },
];
export const countries = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas (the)',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory (the)',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands (the)',
  'Central African Republic (the)',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands (the)',
  'Colombia',
  'Comoros (the)',
  'Congo (the Democratic Republic of the)',
  'Congo (the)',
  'Cook Islands (the)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic (the)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (the) [Malvinas]',
  'Faroe Islands (the)',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories (the)',
  'Gabon',
  'Gambia (the)',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (the)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic (the)",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands (the)',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (the)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger (the)',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands (the)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines (the)',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of North Macedonia',
  'Romania',
  'Russian Federation (the)',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan (the)',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan (Province of China)',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (the)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates (the)',
  'United Kingdom of Great Britain and Northern Ireland (the)',
  'United States Minor Outlying Islands (the)',
  'United States of America (the)',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const states = [
  'AK - Alaska',
  'AL - Alabama',
  'AR - Arkansas',
  'AS - American Samoa',
  'AZ - Arizona',
  'CA - California',
  'CO - Colorado',
  'CT - Connecticut',
  'DC - District of Columbia',
  'DE - Delaware',
  'FL - Florida',
  'GA - Georgia',
  'GU - Guam',
  'HI - Hawaii',
  'IA - Iowa',
  'ID - Idaho',
  'IL - Illinois',
  'IN - Indiana',
  'KS - Kansas',
  'KY - Kentucky',
  'LA - Louisiana',
  'MA - Massachusetts',
  'MD - Maryland',
  'ME - Maine',
  'MI - Michigan',
  'MN - Minnesota',
  'MO - Missouri',
  'MS - Mississippi',
  'MT - Montana',
  'NC - North Carolina',
  'ND - North Dakota',
  'NE - Nebraska',
  'NH - New Hampshire',
  'NJ - New Jersey',
  'NM - New Mexico',
  'NV - Nevada',
  'NY - New York',
  'OH - Ohio',
  'OK - Oklahoma',
  'OR - Oregon',
  'PA - Pennsylvania',
  'PR - Puerto Rico',
  'RI - Rhode Island',
  'SC - South Carolina',
  'SD - South Dakota',
  'TN - Tennessee',
  'TX - Texas',
  'UT - Utah',
  'VA - Virginia',
  'VI - Virgin Islands',
  'VT - Vermont',
  'WA - Washington',
  'WI - Wisconsin',
  'WV - West Virginia',
  'WY - Wyoming',
];
export const sizes = [
  'X-Small',
  'Small',
  'Medium',
  'Large',
  'X-Large',
  '2X-Large',
];
export const sports = [
  'Baseball',
  'Basketball',
  'Cricket',
  'Field Hockey',
  'Football',
  'Table Tennis',
  'Tennis',
  'Volleyball',
];
export const equipment = [
  {
    text: 'Furniture',
    id: 1,
    items: [
      {
        text: 'Tables & Chairs',
        id: 2,
      },
      {
        text: 'Sofas',
        id: 3,
      },
      {
        text: 'Occasional Furniture',
        id: 4,
      },
    ],
  },
  {
    text: 'Decor',
    id: 5,
    items: [
      {
        text: 'Bed Linen',
        id: 6,
      },
      {
        text: 'Curtains & Blinds',
        id: 7,
      },
      {
        text: 'Carpets',
        id: 8,
      },
    ],
  },
];
export const employees = [
  {
    id: 1,
    name: 'Daryl Sweeney',
    reportsTo: null,
    phone: '(555) 924-9726',
    extension: 8253,
    hireDate: new Date('2012-02-07T20:00:00.000Z'),
    fullTime: true,
    position: 'CEO',
    timeInPosition: 2,
  },
  {
    id: 2,
    name: 'Guy Wooten',
    reportsTo: 1,
    phone: '(438) 738-4935',
    extension: 1155,
    hireDate: new Date('2010-03-03T20:00:00.000Z'),
    fullTime: true,
    position: 'Chief Technical Officer',
    timeInPosition: 1,
  },
  {
    id: 3,
    name: 'Priscilla Frank',
    reportsTo: 1,
    phone: '(278) 927-2684',
    extension: 4183,
    hireDate: new Date('2014-11-30T00:00:00.000Z'),
    fullTime: true,
    position: 'Chief Product Officer',
    timeInPosition: 2,
  },
  {
    id: 4,
    name: 'Ursula Holmes',
    reportsTo: 3,
    phone: '(302) 760-2034',
    extension: 2226,
    hireDate: new Date('2011-06-06T00:00:00.000Z'),
    fullTime: true,
    position: 'EVP, Product Strategy',
    timeInPosition: 4,
  },
  {
    id: 5,
    name: 'Anika Vega',
    reportsTo: 1,
    phone: '(910) 714-1802',
    extension: 6353,
    hireDate: new Date('2010-02-25T00:00:00.000Z'),
    fullTime: true,
    position: 'Chief Process Officer',
    timeInPosition: 5,
  },
  {
    id: 6,
    name: 'Moses Duncan',
    reportsTo: 64,
    phone: '(421) 611-4814',
    extension: 669,
    hireDate: new Date('2010-05-24T00:00:00.000Z'),
    fullTime: true,
    position: 'Software Developer',
    timeInPosition: 6,
  },
  {
    id: 7,
    name: 'Nevada Hart',
    reportsTo: 1,
    phone: '(254) 220-1576',
    extension: 6649,
    hireDate: new Date('2015-08-17T00:00:00.000Z'),
    fullTime: true,
    position: 'Chief Financial Officer',
    timeInPosition: 6,
  },
  {
    id: 8,
    name: 'Hunter Fry',
    reportsTo: 1,
    phone: '(766) 358-9858',
    extension: 3741,
    hireDate: new Date('2011-02-12T00:00:00.000Z'),
    fullTime: false,
    position: 'General Counsel',
    timeInPosition: 3,
  },
  {
    id: 9,
    name: 'Kuame Carrillo',
    reportsTo: 8,
    phone: '(192) 383-1305',
    extension: 9228,
    hireDate: new Date('2011-02-22T00:00:00.000Z'),
    fullTime: true,
    position: 'Associate General Councel',
    timeInPosition: 0,
  },
  {
    id: 10,
    name: 'Vernon Ballard',
    reportsTo: 5,
    phone: '(702) 185-8890',
    extension: 9242,
    hireDate: new Date('2015-06-26T00:00:00.000Z'),
    fullTime: true,
    position: 'Director Facilities',
    timeInPosition: 2,
  },
];
